name: Playwright Tests
on:
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: blacksmith

    env:
      VITE_SUPABASE_URL: ${{ vars.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ vars.VITE_SUPABASE_ANON_KEY }}
      TEST_SUPABASE_SERVICE_ROLE_KEY: ${{ vars.TEST_SUPABASE_SERVICE_ROLE_KEY }}
      TEST_MAILPIT_URL: ${{ vars.TEST_MAILPIT_URL }}

    strategy:
     fail-fast: true
     matrix:
       browser: [chromium, firefox, webkit]

    steps:
      - uses: actions/checkout@v6

      - uses: supabase/setup-cli@v1
        with:
           version: latest

      - uses: useblacksmith/stickydisk@v1
        with:
          key: supabase-pgdata-${{ runner.os }}-shard$-${{ matrix.browser }}
          path: ~/.supabase/data

      - name: Start Supabase local development setup
        run: supabase start --exclude edge-runtime,imgproxy,logflare,postgres-meta,realtime,storage-api,supavisor,vector

      - uses: useblacksmith/setup-node@v5
        with:
          node-version-file: ".nvmrc"

      - name: Cache npm dependencies
        id: cache-npm-deps
        uses: useblacksmith/stickydisk@v1
        with:
          key: ${{ runner.os }}-npm-cache
          path: ~/.npm

      - name: Install dependencies
        run: npm ci

      - uses: useblacksmith/stickydisk@v1
        with:
          key: playwright-browsers-${{ runner.os }}-${{ matrix.browser }}
          path: ~/.cache/ms-playwright

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps "${{ matrix.browser }}"

      - name: Wait for Supabase to be ready
        run: |
          timeout=600
          counter=0
          until curl -s http://127.0.0.1:54321/rest/v1/ >/dev/null; do
            if [ $counter -gt $timeout ]; then
              echo "Timed out waiting for Supabase"
              exit 1
            fi
            echo "Waiting for Supabase to be ready..."
            sleep 1
            counter=$((counter + 1))
          done
          echo "Supabase is ready!"

      - name: Run Playwright tests
        run: npm run test -- --project="${{ matrix.browser }}"

      - uses: actions/upload-artifact@v4
        if: ${{ failure() && !cancelled()  }}
        with:
          name: ${{ matrix.browser }}-test-results
          path: test-results
          retention-days: 30

      - name: Stop Supabase local development setup
        if: always()
        run: supabase stop
